drop table if exists Orders
drop table if exists Products
drop table if exists Customers

Create table Products
	(ID int Primary key identity (1000,1),
	ProdName varchar(30),
	Price real 
	)


create table Customers
	([ID] int Primary key identity (2000,1),
	[Firstname] varchar(30),
	[Lastname] varchar(30),
	[Cardnumber] varchar (16)
	)


create table Orders
	([ID] int primary key identity (3000,1),
	[ProdID] int foreign key references Products(ID),
	[CustID] int foreign key references Customers(ID)
	);


-- add at least 3 records into each table.

Insert into Products ( ProdName,Price)
	values 
		( 'plain_pizza', 1.0), 
		( 'mushroom_pizza', 1.75), 
		( 'white_pizza', 2.5)

Insert into Customers 
	values
		('Leighton', 'Baines', str(FLOOR(RAND()*(999-100+1)+100))), 
		('Marie', 'Curie', str(FLOOR(RAND()*(999-100+1)+100))),
		('Seamus', 'Coleman', str(FLOOR(RAND()*(999-100+1)+100)))

insert into Orders values (1000, 2000), (1001, 2001), (1002, 2002)


-- add product iPhone priced at $200.
insert into Products values ('iphone',200)

-- add customer Tina Smith.
insert into Customers values ('Tina', 'Smith', str(FLOOR(RAND()*(999-100+1)+100)))

-- create order for Tina Smith bought an iPhone.
insert into Orders values ((Select ID from Products where ProdName = 'iphone'),
	(Select ID from Customers where Firstname = 'Tina' and Lastname = 'Smith')
	)
insert into Orders values ((Select ID from Products where ProdName = 'iphone'),
	(Select ID from Customers where Firstname = 'Seamus' and Lastname = 'COleman')
	)

-- report all orders by Tina Smith.
--Select * from Orders where CustID = (Select ID from Customers where Firstname = 'Tina' and Lastname = 'Smith')



-- increase the price of iPhone to $250.
update Products
	set Price = 250
	where ProdName = 'iphone'


-- report all revenue generated by sales of iPhone. 
select sum(Price) as revenue
	from 
		Products join Orders 
		on Products.ID = Orders.ProdID
			where Products.ProdName = 'iphone'
--same but without joins
--select
--	(select Price from Products where ProdName = 'iphone')
--	 * 
--	(select count(ProdID) from Orders where ProdID = (
--		select ID from Products where Prodname = 'iphone'
--		)
--	)



 --Select * from Products
 --Select * from Customers
 --Select * from Orders
